version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "pip"
      include: "scope"
    ignore:
      - dependency-name: "django"
        versions: ["4.2.x"]
      - dependency-name: "djangorestframework"
        versions: ["3.14.x"] 